#ifndef UAD_CONFIG_H
#define UAD_CONFIG_H

#define D3DX 1
#define OGLES20 2
#define OGLES30 3
#define OGL 4

#define DRIVER_SELECTED D3DX

#if   DRIVER_SELECTED == OGLES20
#define USING_OPENGL_ES20
#elif DRIVER_SELECTED == OGLES30
#define USING_OPENGL_ES30
#elif DRIVER_SELECTED == D3DX
#define USING_D3D11
#elif DRIVER_SELECTED == OGL
#define USING_OPENGL
#endif

#if defined(USING_OPENGL_ES20) || defined(USING_OPENGL_ES30)  || defined(USING_OPENGL)
#define USING_GL_COMMON
#endif

#define USE_POINTLIGHT
#define USE_GLOBALLIGHT
#define USE_TEXCOORD0
#define USE_DIFFUSE
#endif